import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export const runtime = "nodejs";

interface GrokSummaryBody {
  meetingId: string;
  meetingTitle: string;
  meetingDate: string;
  agendaPdfUrl: string;
}

function extractMessageContent(content: unknown): string {
  if (typeof content === "string") {
    return content.trim();
  }

  if (Array.isArray(content)) {
    return content
      .map((part) => {
        if (typeof part === "string") return part;
        if (
          part &&
          typeof part === "object" &&
          "text" in part &&
          typeof (part as { text?: unknown }).text === "string"
        ) {
          return (part as { text: string }).text;
        }
        return "";
      })
      .join("\n")
      .trim();
  }

  return "";
}

export async function POST(request: Request) {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = (await request.json()) as Partial<GrokSummaryBody>;
    const meetingId = body.meetingId?.trim();
    const meetingTitle = body.meetingTitle?.trim();
    const meetingDate = body.meetingDate?.trim();
    const agendaPdfUrl = body.agendaPdfUrl?.trim();

    if (!meetingId || !meetingTitle || !meetingDate || !agendaPdfUrl) {
      return NextResponse.json(
        { error: "Missing required payload" },
        { status: 400 }
      );
    }

    const xaiApiKey = process.env.XAI_API_KEY;
    if (!xaiApiKey) {
      return NextResponse.json(
        { error: "XAI_API_KEY is not configured" },
        { status: 500 }
      );
    }

    const model = process.env.XAI_MODEL || "grok-4-1-fast-reasoning";

    const prompt = [
      "Analyse l'ordre du jour de réunion accessible via ce PDF:",
      agendaPdfUrl,
      "",
      "Contexte:",
      `- Titre: ${meetingTitle}`,
      `- Date: ${meetingDate}`,
      "",
      "Réponds uniquement en markdown en français, avec les sections exactes:",
      "## Résumé",
      "## Décisions et points clés",
      "## To-dos à venir",
      "## Événements et échéances",
      "",
      "Contraintes:",
      "- Utilise des listes à puces courtes.",
      "- Si une information est absente du PDF, écris 'Non précisé' pour cet élément.",
      "- N'invente pas de faits non présents dans le document.",
    ].join("\n");

    const grokResponse = await fetch("https://api.x.ai/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${xaiApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model,
        temperature: 0.2,
        messages: [
          {
            role: "system",
            content:
              "You extract reliable structured meeting information from agenda documents and return concise markdown.",
          },
          {
            role: "user",
            content: prompt,
          },
        ],
      }),
    });

    const grokPayload = (await grokResponse.json()) as {
      error?: { message?: string };
      choices?: Array<{ message?: { content?: unknown } }>;
    };

    if (!grokResponse.ok) {
      return NextResponse.json(
        {
          error:
            grokPayload.error?.message ||
            "Grok request failed while generating meeting summary",
        },
        { status: 502 }
      );
    }

    const summary = extractMessageContent(
      grokPayload.choices?.[0]?.message?.content
    );

    if (!summary) {
      return NextResponse.json(
        { error: "Empty summary generated by Grok" },
        { status: 502 }
      );
    }

    const { data: updatedMeeting, error: updateError } = await supabase
      .from("meetings")
      .update({ agenda_ai_summary: summary })
      .eq("id", meetingId)
      .select("id")
      .maybeSingle();

    if (updateError) {
      return NextResponse.json(
        { error: updateError.message || "Failed to save meeting summary" },
        { status: 500 }
      );
    }

    if (!updatedMeeting) {
      return NextResponse.json(
        { error: "Meeting not found or not writable" },
        { status: 404 }
      );
    }

    return NextResponse.json({ summary });
  } catch (error) {
    return NextResponse.json(
      {
        error:
          error instanceof Error
            ? error.message
            : "Unexpected error while generating Grok summary",
      },
      { status: 500 }
    );
  }
}
